### PR TITLE
fixes #231 (three year old issue)

### LINKED ISSUE #231: Inconsistent Share Behaviour when Access from App
## Bug Report

Sharing an article triggers the os share dialog. Sharing a comment does not.

**Steps to Reproduce**

- try to share a comment

**Actual Results**

d12ce832fde320525149da05f91089db1c439cee470b86e974a7bc4e974f0d36

**Expected Results**

OS dialog

**Environment**

- Browser: iOS App 1.0.1

**Possible Solutions**

Use share post message everywhere :)

### PR DESCRIPTION
**Pull request by ovbm**
closes #231 

doesn't address share icon inconsitency which should be addressed in styleguide.

https://user-images.githubusercontent.com/20746301/107572249-4c361a00-6bec-11eb-93c5-17eee0d7ddf5.mov

### CODE REVIEW

File: components/Discussion/Comments.js [hunk 1]
```diff
@@ -332,7 +334,19 @@ const Comments = props => {
...
             },
             shareComment: comment => {
-              setShareUrl(getFocusUrl(discussion, comment))
+              if (inNativeApp) {
+                postMessage({
+                  type: 'share',
+                  payload: {
+                    title: discussion.title,
+                    url: getFocusUrl(discussion, comment),
+                    subject: discussion.title || '',
```
Comment (tpreusse) [inline components/Discussion/Comments.js:343]:
```suggestion
                    subject: t('discussion/share/emailSubject', {
                      title: discussion.title
                    }),
```

**Review by tpreusse — APPROVED** [review]
Looks good. One small thing: let's add a bit of kontext to the subject line with the existing `discussion/share/emailSubject` message
